name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        uses: sibiraj-s/action-eslint@v3
        with:
          ignore-path: |
            .eslintignore
            .gitignore
          ignore-pattern: 'dist/'
          extensions: 'js,jsx,ts,tsx'
          annotations: true
          github-workspace: ${{ github.workspace }}
          eslint-args: '--max-warnings=0'

